### ISSUE TITLE
Adding commas in song name adds a %2C in its name for whatever reason

### ISSUE THREAD

**Issue by Peenicks** [JacobMcAuley/playlist_import#13]
![image](https://user-images.githubusercontent.com/13890194/87852591-80ba4f80-c903-11ea-8a09-c293bf103ce2.png)

**Comment by JacobMcAuley** [comment]
Hi, this is likely because of the way it's handled by the OS when it is translated literally.

Recall that the OS stores the names using special characters to denote certain descriptors, %2C in this case represents commas. Something like %20 would represent spaces.
I can take a look, but it's possible this is just a result of converting the literal file name from the ASCII level back into Foundry.

**Comment by Nova-Katt** [comment]
Oh, happy I decided to take a look at the git after installing the module, before starting to import music. I'm pretty sure some of the files I have, have commas in them. But now I know to fix that before even trying to import them! Especially considering the other issue where it was mentioned that importing a song, then deleting it from the ingame playlist, renders it impossibleto ever be imported again. xD weird, but now i know before even trying! :D thanks!
....now if i could just... find some kind of reasonable organization of my music, ambience, and sound effects xD
