### ISSUE TITLE
A folder starting with number will have the number removed after being imported as a playlist

### ISSUE THREAD

**Issue by PBobovsky** [JacobMcAuley/playlist_import#32]
A folder with music starting with a number (example: "29th planet") will have the number removed when imported as a playlist (so the result is "Th planet"). 
Expected result is to keep the number.

**Comment by JacobMcAuley** [comment]
Hi, PB.
Sorry for the late response, I had personal issues I needed to take take of.

As for your issue, this is a result of the regex used to filter and name files. You can modify it yourself within the module settings. That being said, the removal of the "29" in the "29th planet" is a result of the filter looking for playlists that start with a number, with the intention of removing names like "12312_Going_To_Planet_29" into "Going To Planet 29". 

Since it's hard to make a catch all that gets every naming convention, I'm afraid I can't help much here. However, if you manage to come up with a REGEX that covers that edgecase, I'll incorporate it.

Best,
Jacob
